# Site settings
title:          삽질 History
description:    "Yongjun's Dev Blog"
url:            "https://ruzun88.github.io"

# Google Analytics
#google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Yongjun Cho
  url:          https://www.github.com/ruzun88
  email:        aristotle@kakao.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-remote-theme
  # - jemoji #Uncomment this to allow emoji in your post

remote_theme: chesterhow/tale

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]


# Disqus (Set to your disqus id)
#disqus:         jekyll-tale